[Android] Bump NDK API level to 24
Needed to fix error with libp2p:

| /usr/include/c++/v1/fstream:1032:13: error: use of undeclared identifier 'fseeko'
|         if (fseeko(__file_, -__c, SEEK_CUR))
|             ^